### ISSUE TITLE
How to save html output ?

### ISSUE THREAD

**Issue by Twistedmock** [dsecuredcom/ffufPostprocessing#2]
I have used this command to generate additional html report 

ffufPostprocessing -result-file /tmp/random/results.json -bodies-folder /tmp/random/bodies/ -new-result-file results.json  -generate-html-report -html-report-path ~/temp/result.html

But I got no result file. Did I miss anything?

![2023-09-26_17-46](https://github.com/Damian89/ffufPostprocessing/assets/88490703/64111716-2ec2-4afa-88fe-ebcdbaa3a85c)

**Comment by Damian89** [comment]
Take a look at the code.
I prepared some more flags (But they are not documented in readme for a reason) because I intended to implement a html report based on datatables, but frankly speaking - I dont have time currently ;)
That being said:
This feature is not implemented.
